// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXYl3NZqvOO4k1oT_v4_7T2FbhI6bugDU',
    appId: '1:890052968608:web:49eb9025d29aef41e749c5',
    messagingSenderId: '890052968608',
    projectId: 'car-store-2024',
    authDomain: 'car-store-2024.firebaseapp.com',
    databaseURL: 'https://car-store-2024-default-rtdb.firebaseio.com',
    storageBucket: 'car-store-2024.appspot.com',
    measurementId: 'G-9KH9GME2LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5UHwKmbZqxs7ZhtiMtgVnlVSbEFBHPhI',
    appId: '1:890052968608:android:bca628d47d88251be749c5',
    messagingSenderId: '890052968608',
    projectId: 'car-store-2024',
    databaseURL: 'https://car-store-2024-default-rtdb.firebaseio.com',
    storageBucket: 'car-store-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpOwQMG62OQRi0P3PWRZ-6ayxgL2fa2gg',
    appId: '1:890052968608:ios:6f2f333f4a302a9fe749c5',
    messagingSenderId: '890052968608',
    projectId: 'car-store-2024',
    databaseURL: 'https://car-store-2024-default-rtdb.firebaseio.com',
    storageBucket: 'car-store-2024.appspot.com',
    iosBundleId: 'com.example.carStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpOwQMG62OQRi0P3PWRZ-6ayxgL2fa2gg',
    appId: '1:890052968608:ios:6f2f333f4a302a9fe749c5',
    messagingSenderId: '890052968608',
    projectId: 'car-store-2024',
    databaseURL: 'https://car-store-2024-default-rtdb.firebaseio.com',
    storageBucket: 'car-store-2024.appspot.com',
    iosBundleId: 'com.example.carStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXYl3NZqvOO4k1oT_v4_7T2FbhI6bugDU',
    appId: '1:890052968608:web:c53c62bee6675788e749c5',
    messagingSenderId: '890052968608',
    projectId: 'car-store-2024',
    authDomain: 'car-store-2024.firebaseapp.com',
    databaseURL: 'https://car-store-2024-default-rtdb.firebaseio.com',
    storageBucket: 'car-store-2024.appspot.com',
    measurementId: 'G-D0Q5RL33WM',
  );

}